version: "3.7"

services:
  membership-postgresd:
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=membership
      - POSTGRES_USER=membership
    ports:
      - "5433:5432" # for development
    networks:
      - auth_intranet

networks:
  auth_intranet:
    external: true