services:
  membership-postgresd:
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=membership
      - POSTGRES_USER=membership
    ports:
      - "5433:5432" # for development

  keycloak:
    image: quay.io/keycloak/keycloak:26.5.4
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8180:8080"
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
